version: '3.7'
services:
  nodejs-api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: asadraza270/cognigy_car_api:latest  
    ports:
      - "3000:3000"
    container_name: nodejs-api
    links:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./data/:/data/db
